apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  serviceAccountName: jenkins
  containers:
  - name: ubuntu
    image: ubuntu:latest
    tty: true
    # Just spin & wait forever
    # command: [ "/bin/bash", "-c", "--" ]
    # args: [ "while true; do sleep 30; done;" ]
